[package]
name = "kloop-core"
version.workspace = true
edition.workspace = true

[dependencies]
kloop-protocol = { workspace = true }
kloop-provider = { workspace = true }

anyhow = { workspace = true }
futures = { workspace = true }
globset = { workspace = true }
grep-regex = { workspace = true }
grep-searcher = { workspace = true }
ignore = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tree-sitter = { workspace = true }
tree-sitter-bash = { workspace = true }
