[package]
name = "kloop"
version.workspace = true
edition.workspace = true

[dependencies]
kloop-core = { workspace = true }
kloop-protocol = { workspace = true }
kloop-provider = { workspace = true }

anyhow = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
toml = { workspace = true }
