[package]
name = "kloop-server"
version.workspace = true
edition.workspace = true

[dependencies]
kloop-core = { workspace = true }
kloop-protocol = { workspace = true }

anyhow = { workspace = true }
getrandom = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
kloop-provider = { workspace = true }
