[package]
name = "kloop-tui"
version.workspace = true
edition.workspace = true

[dependencies]
kloop-core = { workspace = true }
kloop-protocol = { workspace = true }

anyhow = { workspace = true }
crossterm = { workspace = true }
futures = { workspace = true }
ratatui = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
